DROP TABLE TRAB_DIM_CARGO;
DROP TABLE TRAB_DIM_DEPARTAMENTO;
DROP TABLE TRAB_DIM_DIVISAO;
DROP TABLE TRAB_DIM_FUNCIONARIO;
DROP TABLE TRAB_FATO_FOLHA;

CREATE TABLE TRAB_DIM_CARGO(
	SK_Cargo    		NUMBER NOT NULL,
	CargoID 			NUMBER NOT NULL,
	Desc_Cargo 			VARCHAR(50) NOT NULL,
	Piso 				FLOAT(126),
	Media 				FLOAT(126),
	Maior               FLOAT(126),	
	Dtc_Inicio			DATE,
	Dtc_Fim				DATE,
 CONSTRAINT PK_Dim_SK_Cargo PRIMARY KEY (
	CargoID 
));

CREATE TABLE TRAB_DIM_DEPARTAMENTO(
	SK_Departamento     NUMBER NOT NULL,
	DepartamentoID 		NUMBER NOT NULL,
	Desc_Departamento 	VARCHAR(50),
	Dtc_Inicio			DATE,
	Dtc_Fim				DATE,	
 CONSTRAINT PK_Dim_SK_Depto PRIMARY KEY  
(
	DepartamentoID 
));

CREATE TABLE TRAB_DIM_DIVISAO(
	SK_Divisao      	NUMBER NOT NULL,
	DivisaoID 			NUMBER NOT NULL,
	Desc_Divisao 		VARCHAR(50),
	Dtc_Inicio			DATE,
	Dtc_Fim				DATE,	
 CONSTRAINT PK_Dim_SK_Divisao PRIMARY KEY  
(
	DivisaoID 
));

CREATE TABLE TRAB_DIM_FUNCIONARIO(
	SK_Funcionario      	NUMBER NOT NULL,	
	FuncionarioID 			NUMBER NOT NULL,
	Nome_Funcionaro 		VARCHAR(50),
	Sobrenome_Funcionaro 	VARCHAR(50),
	Dtc_Inicio				DATE,
	Dtc_Fim					DATE,		
 CONSTRAINT PK_Dim_SK_Func PRIMARY KEY  
(
	FuncionarioID 
));
CREATE TABLE TRAB_FATO_FOLHA(
	SK_Cargo   				NUMBER NOT NULL,
	SK_Funcionario 			NUMBER NOT NULL,
	SK_Divisao 				NUMBER NOT NULL,	SK_Departamento 		NUMBER NOT NULL,
	SK_TEMPO				NUMBER NOT NULL,
	Salario_Valor			FLOAT(126),
	Qtd_Funcionarios		NUMBER NOT NULL,
 CONSTRAINT PK_Fato_FolhaID PRIMARY KEY  
(
	SK_Cargo,
	SK_Funcionario,
	SK_Divisao,
	SK_Departamento,
	SK_TEMPO
));


  CREATE TABLE "REP_OWB"."TRAB_DIM_TEMPO" 
   (	"SK_TEMPO" NUMBER NOT NULL ENABLE, 
	"DES_DATA_DIA" VARCHAR2(25 BYTE), 
	"DTC_DATA" DATE, 
	"NUM_ANO" NUMBER(4,0), 
	"NUM_MES" NUMBER(3,0), 
	"NUM_DIA" NUMBER(3,0), 
	"NUM_QUADRIMESTRE" NUMBER(3,0), 
	"NUM_TRIMESTRE" NUMBER(2,0), 
	"DES_QUINZENA" VARCHAR2(12 BYTE), 
	"DES_QUADRIMESTRE" VARCHAR2(12 BYTE), 
	"NUM_BIMESTRE" NUMBER(3,0), 
	"DES_BIMESTRE" VARCHAR2(12 BYTE), 
	"DES_ANO_MES" VARCHAR2(8 BYTE), 
	"DES_DIA" VARCHAR2(7 BYTE), 
	"NUM_SEMESTRE" NUMBER(3,0), 
	"DES_MES_ANO_NUMERICO" VARCHAR2(7 BYTE), 
	"DES_TRIMESTRE" VARCHAR2(12 BYTE), 
	"IND_FINAL_SEMANA" CHAR(1 BYTE), 
	"DES_MES" VARCHAR2(15 BYTE), 
	"NUM_QUINZENA" NUMBER(3,0), 
	"DES_MES_ANO_COMPLETO" VARCHAR2(30 BYTE), 
	"DES_SEMESTRE" VARCHAR2(12 BYTE), 
	"NUM_NIVEL" NUMBER(1,0), 
	"DES_MES_ANO" VARCHAR2(8 BYTE), 
	 CONSTRAINT "TRAB_DIM_TEMPO_KEY_PK" PRIMARY KEY ("SK_TEMPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;















