USE dados;
INSERT INTO `dados`.`INFRA_MD`
(`dat_infracao`,
`tip_abordagem`,
`ind_assinou_auto`,
`ind_veiculo_estrangeiro`,
`ind_sentido_trafego`,
`uf_placa`,
`regiao_placa`,
`uf_infracao`,
`regiao_infracao`,
`num_br_infracao`,
`num_km_infracao`,
`nom_municipio`,
`cod_infracao`,
`descricao_abreviada`,
`enquadramento`,
`data_inicio_vigencia`,
`data_fim_vigencia`,
`med_realizada`,
`med_considerada`,
`exc_verificado`,
`especie`,
`nome_veiculo_marca`,
`nom_modelo_veiculo`, `hora`, `gravidade`, `responsabilidade`, `competencia`, `valor`, `dia_infracao`, `periodo_infracao`)
SELECT 
	A.`dat_infracao`,
	A.`tip_abordagem`,
	A.`ind_assinou_auto`,
	A.`ind_veiculo_estrangeiro`,
	A.`ind_sentido_trafego`,
	A.`uf_placa`,
	A.`regiao_placa`,
	A.`uf_infracao`,
	A.`regiao_infracao`,
	A.`num_br_infracao`,
	A.`num_km_infracao`,
	A.`nom_municipio`,
	A.`cod_infracao`,
	A.`descricao_abreviada`,
	A.`enquadramento`,
	A.`data_inicio_vigencia`,
	A.`data_fim_vigencia`,
	A.`med_realizada`,
	A.`med_considerada`,
	A.`exc_verificado`,
	A.`especie`,
	A.`nome_veiculo_marca`,
	A.`nom_modelo_veiculo`,
	A.`hora`,
	B.gravidade, B.responsabilidade, B.competencia, B.valor,
	CASE WHEN DAY(A.`dat_infracao`) BETWEEN 0 and 7 THEN "SEM_1" WHEN DAY(A.`dat_infracao`) BETWEEN 8 and 14 THEN "SEM_2" WHEN DAY(A.`dat_infracao`) BETWEEN 15 and 21 THEN "SEM_3" WHEN DAY(A.`dat_infracao`) >= 22 THEN "SEM_4" END,
	CASE WHEN A.`hora` BETWEEN '06:00:00' AND '11:59:59' THEN "MANHA" WHEN A.hora BETWEEN '12:00:00' AND '17:59:59' THEN "TARDE" ELSE "NOITE" END
FROM TAB_INFRACAO_BASE AS A LEFT JOIN TAB_DADOS_INFRA AS B ON B.num_infracao = A.cod_infracao WHERE B.enquadramento IS NOT NULL;
  

