USE dados;
SET SQL_SAFE_UPDATES = 0;
UPDATE dados.INFRA_MD
SET responsabilidade = 'CONDUTOR'
WHERE responsabilidade = 'A
CONDUTOR';
SET SQL_SAFE_UPDATES = 0;
UPDATE dados.INFRA_MD SET competencia = 'MUNICIPIO' WHERE competencia = 'MUNICIPAL/RODOV';
SET SQL_SAFE_UPDATES = 0;
UPDATE dados.INFRA_MD SET competencia = 'ESTADO' WHERE competencia = 'ESTADUAL/RODOV';
SET SQL_SAFE_UPDATES = 0;
UPDATE dados.INFRA_MD SET competencia = 'ESTADO' WHERE competencia = 'ESTADUAL';
SET SQL_SAFE_UPDATES = 0;
UPDATE dados.INFRA_MD SET competencia = 'ESTADO/MUNICIPIO' WHERE competencia = 'EST/MUNIC/RODOV';
SET SQL_SAFE_UPDATES = 0;
UPDATE dados.INFRA_MD SET competencia = 'ESTADO/MUNICIPIO' WHERE competencia = 'MUNICIPAL/ESTADUAL';
SET SQL_SAFE_UPDATES = 0;
UPDATE dados.INFRA_MD SET competencia = 'MUNICIPIO' WHERE competencia = 'MUNICIPAL';
SET SQL_SAFE_UPDATES = 0;
UPDATE dados.INFRA_MD SET competencia = 'MUNICIPIO' WHERE competencia = 'MUNICÍPIO';
SET SQL_SAFE_UPDATES = 0;
UPDATE dados.INFRA_MD SET competencia = 'ESTADO/MUNICIPIO' WHERE competencia = 'MUNICIPIO/ESTADO';	