/*
-- 
-- ATIVIDADE 2/2

-- Equipe 5: Camila Oliveira e Rosana Cardoso
--
-- Script: 4. FC_INS_GASTO_PARLAMENTAR
--
-- Testar a Função chamada FC_INS_GASTO_PARLAMENTAR
--

*/
-- EXECUTAR FUNÇÃO
SET SERVEROUTPUT ON

DECLARE
  RETORNO NUMBER;
BEGIN
  RETORNO:=FC_INS_GASTO_PARLAMENTAR;
  DBMS_OUTPUT.PUT_LINE(RETORNO);
END;

-- CHECAR TABELAS
SELECT * FROM LOG_CARGA;
SELECT * FROM GASTO_PARLAMENTAR;
