/*
-- 
-- ATIVIDADE 2/2

-- Equipe 5: Camila Oliveira e Rosana Cardoso
--
-- Script: 1.2. PKG_LOG_CARGA_Corpo
--
-- Criar Corpo do Pacote PKG_LOG_CARGA

*/

CREATE OR REPLACE PACKAGE BODY PKG_LOG_CARGA AS

  -- PROCEDURE PARA INSERIR DADOS NA TABELA LOG_CARGA
  PROCEDURE UP_INS_LOGCARGA (id_log NUMBER, des_log VARCHAR2, dt_ini DATE) AS
  BEGIN
    INSERT INTO LOG_CARGA (IDE_LOG_CARGA, DES_LOG_CARGA, DTC_INICIO)
    VALUES (id_log, des_log, dt_ini);
    COMMIT;
  END;

  -- PROCEDURE PARA ATUALIZAR DADOS NA TABELA LOG_CARGA
  PROCEDURE UP_UPD_LOGCARGA (id_log NUMBER, dt_fim DATE, erro VARCHAR2) AS
  BEGIN
    UPDATE LOG_CARGA SET DTC_FIM = dt_fim,
                         DES_ERRO = ERRO
     WHERE IDE_LOG_CARGA = id_log;
    COMMIT;
  END;

  -- FUNÇÃO QUE VERIFICA SE NA ULTIMA CARGA OCORREU ALGUM ERRO  
  FUNCTION FC_VERIFICA_ERRO 
    RETURN NUMBER
  AS
    RETORNO VARCHAR2(500);
  BEGIN
  
    SELECT LOG_CARGA.DES_ERRO INTO RETORNO 
      FROM (SELECT * FROM LOG_CARGA ORDER BY IDE_LOG_CARGA DESC) LOG_CARGA
     WHERE LOG_CARGA.DES_LOG_CARGA = 'CARGA DADOS' AND
           ROWNUM = 1
    ORDER BY IDE_LOG_CARGA;
    IF RETORNO IS NULL THEN
       RETURN 0;
    ELSE
       RETURN 1;
    END IF;
    
  END;
  
END PKG_LOG_CARGA;