/*
-- 
-- ATIVIDADE 2/2

-- Equipe 5: Camila Oliveira e Rosana Cardoso
--
-- Script: 5. UP_EXECUTA_CARGA
--
-- Criar Procedure UP_EXECUTA_CARGA
--
*/

CREATE OR REPLACE PROCEDURE UP_EXECUTA_CARGA (P_ORDEM NUMBER) AS
  RET_ERRO NUMBER;
  RET_ERRO_INT NUMBER;
  RETORNO NUMBER;
  REGISTRO NUMBER;
  PROCESSO_GERAL NUMBER;
  MENSAGEM VARCHAR2(50);
  ERRO VARCHAR2(500);
  
  BEGIN

    RET_ERRO := PKG_LOG_CARGA.FC_VERIFICA_ERRO;

    REGISTRO := LOGCARGA_SEQ.nextval;
    PKG_LOG_CARGA.UP_INS_LOGCARGA(REGISTRO, 'CARGA DADOS', CURRENT_DATE);
    PROCESSO_GERAL := REGISTRO;    

    
    IF RET_ERRO = 1 THEN

       REGISTRO := LOGCARGA_SEQ.nextval;
       PKG_LOG_CARGA.UP_INS_LOGCARGA(REGISTRO, 'DELETA DADO TIPO_GASTO', CURRENT_DATE);
       DELETE FROM TIPO_GASTO;
       RET_ERRO_INT := PKG_LOG_CARGA.FC_VERIFICA_ERRO;
       IF RET_ERRO_INT = 1 THEN
          MENSAGEM:= 'OCORREU ERRO';
       END IF;        
       PKG_LOG_CARGA.UP_UPD_LOGCARGA(REGISTRO, CURRENT_DATE, '');  

       REGISTRO := LOGCARGA_SEQ.nextval;
       PKG_LOG_CARGA.UP_INS_LOGCARGA(REGISTRO, 'DELETA DADO PARLAMENTAR', CURRENT_DATE);
       DELETE FROM PARLAMENTAR;
       RET_ERRO_INT := PKG_LOG_CARGA.FC_VERIFICA_ERRO;
       IF RET_ERRO_INT = 1 THEN
          MENSAGEM:= 'OCORREU ERRO';
       END IF;        
       PKG_LOG_CARGA.UP_UPD_LOGCARGA(REGISTRO, CURRENT_DATE, '');          

       REGISTRO := LOGCARGA_SEQ.nextval;
       PKG_LOG_CARGA.UP_INS_LOGCARGA(REGISTRO, 'DELETA DADO GASTO_PARLAMENTAR', CURRENT_DATE);
       DELETE FROM GASTO_PARLAMENTAR;
       RET_ERRO_INT := PKG_LOG_CARGA.FC_VERIFICA_ERRO;
       IF RET_ERRO_INT = 1 THEN
          MENSAGEM:= 'OCORREU ERRO';
       END IF;        
       PKG_LOG_CARGA.UP_UPD_LOGCARGA(REGISTRO, CURRENT_DATE, '');       

    END IF;

    MENSAGEM:='';

    IF P_ORDEM = 1 THEN
       RETORNO := FC_INS_TIPO_GASTO;
       RET_ERRO := PKG_LOG_CARGA.FC_VERIFICA_ERRO;
       IF RET_ERRO = 1 OR RETORNO = 1 THEN
          MENSAGEM := 'OCORREU ERRO';
       END IF;        

       RETORNO := FC_INS_PARLAMENTAR;
       RET_ERRO := PKG_LOG_CARGA.FC_VERIFICA_ERRO;
       IF RET_ERRO = 1 OR RETORNO = 1 THEN
          MENSAGEM := 'OCORREU ERRO';
       END IF;        

       RETORNO := FC_INS_GASTO_PARLAMENTAR;
       RET_ERRO := PKG_LOG_CARGA.FC_VERIFICA_ERRO;
       IF RET_ERRO = 1 OR RETORNO = 1 THEN
          MENSAGEM := 'OCORREU ERRO';
       END IF;        
       
    ELSIF P_ORDEM = 2 THEN

          RETORNO := FC_INS_GASTO_PARLAMENTAR;
          RET_ERRO := PKG_LOG_CARGA.FC_VERIFICA_ERRO;
          IF RET_ERRO = 1 OR RETORNO = 1 THEN
             MENSAGEM := 'OCORREU ERRO';
          END IF;        
          
          RETORNO := FC_INS_TIPO_GASTO;
          RET_ERRO := PKG_LOG_CARGA.FC_VERIFICA_ERRO;
          IF RET_ERRO = 1 OR RETORNO = 1 THEN
             MENSAGEM := 'OCORREU ERRO';
          END IF;        
          
          RETORNO := FC_INS_PARLAMENTAR;  
          RET_ERRO := PKG_LOG_CARGA.FC_VERIFICA_ERRO;
          IF RET_ERRO = 1 OR RETORNO = 1 THEN
             MENSAGEM := 'OCORREU ERRO';
          END IF;        

    END IF;
    
    PKG_LOG_CARGA.UP_UPD_LOGCARGA(PROCESSO_GERAL, CURRENT_DATE, MENSAGEM);  
    REGISTRO := LOGCARGA_SEQ.nextval;
    PKG_LOG_CARGA.UP_INS_LOGCARGA(REGISTRO, 'CARGA DADOS', CURRENT_DATE);
    PKG_LOG_CARGA.UP_UPD_LOGCARGA(REGISTRO, CURRENT_DATE, MENSAGEM);      


  END;


